version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - "4040:4040"
    depends_on:
      - server
  server:
    build: 
      context: ./server
    ports:
      - "8000:8000"
    depends_on:
      - api

  api:
    build: 
      context: ./api
    ports:
      - "5000:5000"

