name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: SRS project environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api:latest -f ./Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
