name: CI/CD DB

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: SRS project environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          login-server: srsproject.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push API client Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/client_db:latest \
            --build-arg VITE_API_SERVER_URL=${{ secrets.VITE_API_SERVER_URL }} \
            --build-arg VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }} \
            --build-arg VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }} \
            --build-arg VITE_AUTH0_CALLBACK_URL=${{ secrets.VITE_AUTH0_CALLBACK_URL }} \
            --build-arg VITE_AUTH0_AUDIENCE=${{ secrets.VITE_AUTH0_AUDIENCE }} \
            --build-arg CLIENT_SSL_CERT=${{ secrets.CLIENT_SSL_CERT }} \
            --build-arg CLIENT_SSL_KEY=${{ secrets.CLIENT_SSL_KEY }} \
            -f ./client/Dockerfile .
          docker push srsproject.azurecr.io/samples/client

      - name: Build and push API server Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/server_db:latest \
          --build-arg SERVER_SSL_CERT=${{ secrets.SERVER_SSL_CERT }} \
          --build-arg SERVER_SSL_KEY=${{ secrets.SERVER_SSL_KEY }} \
          -f ./server/Dockerfile .
          docker push srsproject.azurecr.io/samples/server
